const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('coolapk', {
  call: (operation, args) => ipcRenderer.invoke('coolapk:call', operation, args),
  accounts: () => ipcRenderer.invoke('coolapk:accounts'),
  login: () => ipcRenderer.invoke('coolapk:login'),
  importCookie: cookie => ipcRenderer.invoke('coolapk:import', cookie),
  verify: verificationId => ipcRenderer.invoke('coolapk:verify', verificationId),
  selectAccount: uid => ipcRenderer.invoke('coolapk:select', uid),
  removeAccount: uid => ipcRenderer.invoke('coolapk:remove', uid),
  openExternal: url => ipcRenderer.invoke('coolapk:external', url),
  phone: (operation, args) => ipcRenderer.invoke('coolapk:phone', operation, args),
  openAccountPage: page => ipcRenderer.invoke('coolapk:account-page', page),
  report: target => ipcRenderer.invoke('coolapk:report', target),
  desktop: (operation, args) => ipcRenderer.invoke('coolapk:desktop', operation, args),
  teenager: (operation, args) => ipcRenderer.invoke('coolapk:teenager', operation, args),
  onTeenager: callback => { const handler = (_, value) => callback(value); ipcRenderer.on('coolapk:teenager', handler); return () => ipcRenderer.removeListener('coolapk:teenager', handler); },
  updates: operation => ipcRenderer.invoke('coolapk:updates', operation),
  onUpdates: callback => { const handler = (_, value) => callback(value); ipcRenderer.on('coolapk:updates', handler); return () => ipcRenderer.removeListener('coolapk:updates', handler); },
  saveImage: args => ipcRenderer.invoke('coolapk:save-image', args),
  shareImageData: args => ipcRenderer.invoke('coolapk:share-image', args),
  saveExport: args => ipcRenderer.invoke('coolapk:save-export', args),
  downloads: (operation, args) => ipcRenderer.invoke('coolapk:downloads', operation, args),
  onDownloads: callback => { const handler = (_, value) => callback(value); ipcRenderer.on('coolapk:downloads', handler); return () => ipcRenderer.removeListener('coolapk:downloads', handler); },
  onAccount: callback => { const handler = (_, value) => callback(value); ipcRenderer.on('coolapk:account', handler); return () => ipcRenderer.removeListener('coolapk:account', handler); },
  onCommand: callback => { const handler = (_, value) => callback(value); ipcRenderer.on('coolapk:command', handler); return () => ipcRenderer.removeListener('coolapk:command', handler); },
});
