export type ImageBrowsingMode = 'original' | 'normal' | 'auto';
export type ImageNetwork = { type?: string; saveData?: boolean };
export type ImagePreferences = { version: 1; livePhotoAudio: boolean; browsingMode: ImageBrowsingMode };
export type ImagePreferenceStorage = { getItem(key: string): string | null; setItem(key: string, value: string): void };
export const IMAGE_PREFERENCES_KEY: string;
export const DEFAULT_IMAGE_PREFERENCES: Readonly<ImagePreferences>;
export function normalizeImagePreferences(value: unknown): ImagePreferences;
export function loadImagePreferences(storage: ImagePreferenceStorage): ImagePreferences;
export function saveImagePreferences(storage: ImagePreferenceStorage, value: unknown): ImagePreferences;
export function preferOriginalImage(preferences: unknown, network?: ImageNetwork): boolean;
export function preferredImageSource(item: { source?: string; cover?: string }, preferences: unknown, forceOriginal?: boolean, network?: ImageNetwork): string;
